# Generated by Django 4.1.7 on 2023-03-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todolist',
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
